# Generated by Django 5.1.1 on 2024-09-13 17:10

from django.db import migrations

def create_users_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='users')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RunPython(create_users_group),
    ]
